### PR TITLE
Fixed up Bound Sword

### PR DESCRIPTION
**Pull request by Arcaratus**
-Fixed up Bound Sword to actually be a bound tool
-Fixed Bound Items charge bar bug

### CODE REVIEW

**Comment by TehNut** [comment]
Why doesn't the sword fire the `BoundToolEvent` anymore?

**Comment by Arcaratus** [comment]
It doesn't charge or do anything special

**Comment by Blue64** [comment]
is it planned to eventually? @Arcaratus  @TehNut

**Comment by Arcaratus** [comment]
The Blood Magic IRC channel (#bloodmagic) holds a lot of these content related questions and discussions, you should join to keep up with the latest news and thoughts on upcoming BM content

**Pull request merged**
