### PR TITLE
Bucket recipe fix and Creative Sacrificial Dagger fix

### PR DESCRIPTION
**Pull request by Arcaratus**
-Fixes the Life Essence Bucket recipe
-Make the Creative Sacrificial Dagger creative again!
-Add a config option for the amount of damage done by the Sacrificial Dagger

### CODE REVIEW

**Comment by TehNut** [comment]
1. I already fixed the bucket recipe. https://github.com/WayofTime/BloodMagic/commit/f500ec70ad9da3076b6f51f17c3472519a2eec13
2. You just broke it again.

**Comment by Arcaratus** [comment]
I did that because someone had an empty bucket as a result so...did you test yours?

**Comment by TehNut** [comment]
I did.

**Comment by Arcaratus** [comment]
Well, I tested the above and it works...

**Comment by TehNut** [comment]
The NBT that you provide there does not carry over to the craft. I moved it to our CraftingHandler. Your commit adds extra unnecessary work.

**Comment by Arcaratus** [comment]
Should I undo it?

**Comment by WayofTime** [comment]
Need to fix the JEI compat then, since it shows an empty bucket.

**Comment by TehNut** [comment]
Will do once I get off work

**Pull request merged**
