### PR TITLE
Implement reagent usage for well of suffering

### PR DESCRIPTION
**Pull request by Iamtk421**
Hi,
I'm not really sure of the process of submitting pull requests etc as this is the first time I've ever created one for any project., but would like to suggest this for discussion/consideration.

I was annoyed that reagents couldn't be used to increase the LP gain of the well of suffering, nor increase its range so implemented both using offensa and potentia, as well as lowered LP costs using sanctus.

### CODE REVIEW

**Comment by WayofTime** [comment]
Had a similar thought, but haven't submitted it to git! Will look at this fully when I get home and decide which of them to use ;3

**Comment by Iamtk421** [comment]
I'm glad you decided to put the increased LP return in. :-)
The well of suffering was my first foray into powering rituals with reagents, only to find after trying all of them that it didn't do anything.

I'm curious, if you don't mind, why did you decide to not implement increased range? It was one of the reasons I originally thought of using reagents hoping I'd be able to have a third spawning floor beneath my ritual and not have to do any silly mob transport. Of course I could have just spaced them better too.

It'd be good if the ritual stopped running, or at least stopped using reagent if the altar is full though.

**Comment by TheMadmanofChaos** [comment]
The reason that "The ritual stops functioning when the altar is full" was not implemented was due to how most well of suffering mob farms run. If the ritual stops, the mobs build up, the entity count spirals out of control, the server starts to lag...

We did consider adding that effect as a separate reagent effect, however.

**Comment by Iamtk421** [comment]
Yea, I kind of assumed that.

Now that WayofTime implemented reagent for it, perhaps it would be more appropriate that when full the ritual simply stops using reagent for increased LP.

**Comment by WolfAmaril** [comment]
I'd say that instead of stopping reagent use at full, maybe stop it at 90%, or 95%. My altar is never really "Full" because I keep a blood orb in it at all time to keep constant power going to all my rituals, so I can see that leading to a lot of problems for the end users, if not for the server itself.

**Pull request closed without merging**
