### PR TITLE
Bounding boxes / Collision boxes rework

### PR DESCRIPTION
**Pull request by keraldi**
The following blocks' collision boxes were changed to better fit the model:

- Demon Crystal block
- Alchemy table
- Blood Altar
- Demon Pylon
- Demon Crucible

Collision boxes for some details (Alchemy table devices/details/fluff, Blood Altar fancy corners, pylon antenna and arms, crucible "bowl" (I would be grateful for a proper term) have not been added/changed.

### CODE REVIEW

**Comment by TehNut** [comment]
Screenshots of the new AABBs?

**Comment by keraldi** [comment]
screenshot_20190201_020220 collision box for every crystal
screenshot_20190201_020254 looking at any crystal spike highlights the AABB.
screenshot_20190201_020338 Fits with model (except for the out-of-block corners)
screenshot_20190201_020535 Antenna has its own collision, as do the feet.
screenshot_20190201_020636 Seperate collision for arms & feet, player-sized entity can stand in the center (the pit of the crucible).

**Comment by keraldi** [comment]
screenshot_20190201_020913 Bounding box fits the table model, ignoring the ingredients on top (before the commit it was a normal block pixel higher, the table doesn't have a pixel-flushing (16x16) model), so it's now slightly shorter.

**Comment by keraldi** [comment]
screenshot_20190201_021142

**Pull request merged**
