### PR TITLE
Fix TileSpectral

### PR DESCRIPTION
**Pull request by PackmanDude**
#1904

### CODE REVIEW

**Comment by TehNut** [comment]
This is not a valid fix for the problem.

**Comment by PackmanDude** [comment]
> This is not a valid fix for the problem.

Thanks, I noticed it already. It keeps returning FATAL-errors, because of the Spectral block. Dev said 2 weeks ago he would fix that with some tests and other things 🙁

**Comment by WayofTime** [comment]
If you're referring to https://github.com/WayofTime/BloodMagic/issues/1904 , I said that I'd remove it from the creative tab. I didn't say for sure that I would alter the tile entity itself.

**Comment by PackmanDude** [comment]
Okay.
1.16.5 was released ≈5 years ago and there are still common bugs 😔

**Comment by WayofTime** [comment]
You blow my mind.

**Pull request closed without merging**
