### PR TITLE
Fixed Body Builder 4 Upgrade Requirement

### PR DESCRIPTION
**Pull request by NobleWyrm**
Fixed a typo that made stage 4 of the Body Builder upgrade 5x as difficult as stage 5

### CODE REVIEW

**Comment by TehNut** [comment]
*adds to list of things to make fun of Way for*

**Comment by WayofTime** [comment]
:D

**Comment by NobleWyrm** [comment]
Don't worry, no judging here, I've made far sillier typos. :)

Probably not the best place to ask this, but is there any bug-fixing that you want done and aren't currently working on? I'm loving the newer content, bored, and looking to help, but don't want to duplicate your effort if it can be avoided. Currently just looking through for more of these little quirks to polish away. :)

If it isn't something you already have been working on, I was planning on digging into the weird armor upgrade desyncing between the client and server issue or the Elytra upgrade wackiness.

**Comment by TehNut** [comment]
If you are able to figure out #1065, my hair and sanity would thank you.

**Comment by NobleWyrm** [comment]
No promises, but for the sake of your hair I can take a look at it. 

You were not wrong, this looks hilarious. :D

**Pull request merged**
