### PR TITLE
Create ja_JP.lang (v2.0.0-33)

### PR DESCRIPTION
**Pull request by neconeco2**
Created japanese lang file, loosely...

### CODE REVIEW

**Comment by WayofTime** [comment]
Here is one comment from someone who perused the .lang. https://twitter.com/Wolfofthenyght/status/723833804721369088

**Comment by neconeco2** [comment]
Yes.
It is the difficult part....ummm..
Dusk=daytime>night(dark)=夕暮れ, 夕闇, 黄昏 etc　(better=黄昏)
Dawn=night>daytime(bright)=夜明け, 暁 etc　(better=暁)

but,in japan
attribute : Air, Fire, Earth, Water
Easy to understand.

attribute : 黄昏, 暁
Unfamiliar word and combinations...but cool.
(In fact, I was looking up the meaning in the  Japanese dictionary.)
+++++++++
More accurate translation
dusk=黄昏 <=> dawn=暁

Japanese is easy-to-understand translation.
dusk=光(light) <=> dawn=闇(dark)

Strange combinations a little.
夜明け, 夕暮れ, etc

Do you want to change to the [dusk=黄昏 dawn=暁] ?

**Comment by WayofTime** [comment]
I don't want you to change it if you feel that you have it down pat. I guess if you want the base "name" of the attribute, it would be that dusk represents the coming of night, and dawn represents the coming of day. If you feel happy with what is here, let me know and I'll accept it and call it a day :P

**Comment by neconeco2** [comment]
Fixed >_<

**Pull request merged**
