### PR TITLE
Update fr_FR.lang

### PR DESCRIPTION
**Pull request by AegisLesha**
Update + Massive Overhaul... at last \o/
(I guess it's complete, tell me if it's not :3)

OH AND HAPPY NEW YEAR \o/

### CODE REVIEW

**Comment by AegisLesha** [comment]
Dammit @WayofTime D:

**Comment by AegisLesha** [comment]
Up? :<

**Comment by Adaptivity** [comment]
Now go and update it again :smile:

**Comment by Glomzubuk** [comment]
I must say i disagree with a lot of your translations, i can help if needed.

**Comment by AegisLesha** [comment]
Well help is always appreciated, but to be honest, I don't really see how to make some good translations for this mod :(

**Comment by Glomzubuk** [comment]
Here is my version:
http://pastebin.com/yRUw5941
Tell me if you disagree on some translations, i would be happy to discuss about them.

**Comment by AegisLesha** [comment]
Well I'll take a proper look at it when I'm less busy, (btw, don't you think we should change "Soldat" to "Sbire"?)

**Comment by Glomzubuk** [comment]
Yes, that's a nice change to lesser demons.

**Pull request merged**
