### PR TITLE
Fixed Issue #703; Blocks with MetaData being reset to 0

### PR DESCRIPTION
**Pull request by sensdoggo**
Issue fixed and tested. No longer is changing block metadata.

### CODE REVIEW

**Comment by TehNut** [comment]
@Tombenpotter really? >.>

@lazerzes Could you remove that extra whitespace?

**Comment by WayofTime** [comment]
I'll fix said white space

**Comment by WayofTime** [comment]
Did a formatting pass anyway.

**Comment by Tombenpotter** [comment]
Oops. Hahah, I suck :D

**Pull request merged**
