### PR TITLE
[1.7.10]Update all entries of alchemy

### PR DESCRIPTION
**Pull request by AstonIceDog**
Now,I update all entries of alchemy for 1.7.10.But I don't konw whether is it  in time，because you are committing to 1.9.
This part of entries cost me a whole month.Thanks for @qianzha and Hastur.
And other parts of entries are been translated by @qianzha，@Joccob，@MoXiaoFreak and Myth.

### CODE REVIEW

**Comment by TehNut** [comment]
1.7.10 is not maintained and hasn't been for _several months_. I don't know why you thought this would be worth the time.

**Comment by AstonIceDog** [comment]
I can only use  imageto show that I'm desperate.

**Comment by TehNut** [comment]
Even if this got pulled, it would never get built or released.

**Comment by Dream-Master** [comment]
I using 1.7.10 so sure why not develop the mod a bit.

**Comment by TehNut** [comment]
Because the more we support 1.7, the longer it lasts which is bad. 

Use a resource pack for this.

**Pull request closed without merging**
