### PR TITLE
Create bg_BG.lang

### PR DESCRIPTION
**Pull request by sokratis12GR**
## done until L23

Dont merge them yet.

### CODE REVIEW

**Comment by sokratis12GR** [comment]
woah its been a while xD

**Review by sokratis12GR — COMMENTED** [review]
Updated bg_BG.lang

**Comment by sokratis12GR** [comment]
Actually I can't find time for more translations, @TehNut you can merge it now, sorry

**Comment by TehNut** [comment]
If you remove all the un-translated lines, I will merge it

**Comment by sokratis12GR** [comment]
alright give me a sec

**Comment by TehNut** [comment]
Thanks!

**Pull request merged**
