### PR TITLE
Make some messages localized serverside

### PR DESCRIPTION
**Pull request by Adaptivity**
Some messages now localized serverside. If you @WayofTime have some free time, please, convert *ChatComponentText* to *ChatComponentTranslation*, I can't do this because I don't know how to properly add %s tag to the rest of messages.

### CODE REVIEW

**Comment by Adaptivity** [comment]
@WayofTime can be merged again...

**Comment by WayofTime** [comment]
I'll merge it once I have time to fiddle with it :3 Working on a new system atm, and want to make sure nothing breaks in between.

**Comment by Adaptivity** [comment]
Merge?

**Comment by Adaptivity** [comment]
please...

**Comment by Adaptivity** [comment]
Thanks!

**Pull request merged**
