### PR TITLE
Various fixes and improvements (Details in description)

### LINKED ISSUE #421: Teleposer Blacklist
When i try to blacklist the Thaumcraft Auranodes from being teleposed (Thaumcraft:blockAiry:0) it works as expected but nitor (Thaumcraft:blockAiry:1) gets also blacklisted.
(when blacklisting nitor only nitor is blacklisted)
So i guess Metadata 0 is treated as every instance of the block, which should be changed, considering that leaving out the metadata is also blacklisting the whole block?

### LINKED ISSUE #441: Altar z-fights when it is empty
https://github.com/WayofTime/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/common/renderer/model/ModelBloodAltar.java#L53

Check that's greater than 0 before drawing anything...it's pointless to draw anything anyways.

### LINKED ISSUE #459: Blood altar doesn't work with chiseled beacons
I was trying to make a more aesthetically pleasing blood altar (using different beacons that give off different light, but apparently only the vanilla beacon works to make a tier 5 blood altar.

It'd be nice if chiseled beacons could work as well, since they're functionally equivalent and require the actual beacons to make anyway. :)

Edit: Also of note, probably caused by the same thing, are that chiseled glowstone and bloodstone also reduce the altar level, as they're not seen as valid blocks.

Crossposted at Chisel-2/Chisel-2#415 since i'm not sure which mod is at fault.

### PR DESCRIPTION
**Pull request by TehNut**
* Allow the altar to accept any instanceof BlockBeacon. Fixes #459 (Chisel-2/Chisel-2#415)
* Allow disabling of Weak Rituals. Resubmission of #182
* Fixes the Z-fighting issue when a Blood Altar was empty. It would still render blood at the same level as the bottom of the basin. Fixes #441
* Attempted fix at getting free Iron Buckets when non-Iron Buckets were used. Basically just disallows all non-Iron Buckets. Fixes (?) #420 (hehe)
* Drastically improve the Teleposer Blacklist feature. In this new implementation, wildcards are not accepted. I'll attempt to fix that soon. Fixes #421.

### CODE REVIEW

**Comment by Drullkus** [comment]
*I'm the Shizzle artist and I approve of this.*

**Comment by TehNut** [comment]
>**Shizzel**

**Comment by TehNut** [comment]
Nope nope nope. don't merge this yet.

**Comment by TehNut** [comment]
Safe again

**Comment by TehNut** [comment]
Now 100% more chiselable

**Comment by Drullkus** [comment]
> Now 100% more shizzelable

Yes, yes. Indeed

**Comment by TheCricket** [comment]
10/10 Would Chisel again

**Pull request merged**
