### PR TITLE
Augmented capacity rune

### PR DESCRIPTION
**Pull request by BrizzleMFD**
changed the In game text for augmented capacity rune for 1.7.10 to the
correct amount each rune actually gives. Book says 1.5k however each actually gives 2k. I know that 1.8.9 each rune gives 1k so i don't want to break the documentation for that. If I did something wrong please don't use my blood for evil.

### CODE REVIEW

**Comment by WayofTime** [comment]
We are no longer accepting PRs for 1.7.10. Sorry about this!

**Comment by BrizzleMFD** [comment]
All good.

**Comment by Blue64** [comment]
Could still be merged into the master code for anyone who decides to compile it. A sort of "1.7.10 unsupported" branch where you aren't actually pushing it through, but you'll allow bug-fixes for the code.

**Comment by TehNut** [comment]
I think we're completely done with 1.7.10. Merging and all.

**Comment by Blue64** [comment]
Could someone else take over the 1.7.10 portion then?

**Pull request closed without merging**
