### PR TITLE
Account for Use Golems in the fake player check

### PR DESCRIPTION
**Pull request by Vazkii**

### CODE REVIEW

**Comment by WolfAmaril** [comment]
Wouldn't use golems be mostly useless for most blood magic uses, as their speed of use would wind up with them dead long before anything useful was done?

**Comment by Vazkii** [comment]
Might as well check for them anyway, won't hurt ._.

**Comment by WolfAmaril** [comment]
Fair 'nuff.

**Comment by shadowfacts** [comment]
You forgot the closing ]

**Comment by Vazkii** [comment]
If the ] was there it wouldn't work.

**Comment by WayofTime** [comment]
Thanks, Vazkii! Wish people would actually use FakePlayer, but alas~

**Comment by Vazkii** [comment]
The problem with using the forge fake player is that it's an EntityPlayerMP, for all the problems that can cause.

**Comment by WayofTime** [comment]
Boo. Oh well, at least this can be further expanded later. Thanks again.

**Pull request merged**
