### PR TITLE
Add Capability support to Ritual Sones, Finish TE support as well

### PR DESCRIPTION
**Pull request by Alex-hawks**

### CODE REVIEW

**Comment by TehNut** [comment]
I'm trying to understand why this is needed. Way said something about microblocks

**Comment by Alex-hawks** [comment]
The capability portion is needed for me to remake the microblock ritual stones, and I figured that I had to change those classes anyway, so I would finish the Tile Entity support while I was at it.

**Comment by TehNut** [comment]
But _why_ is it required?

**Comment by Alex-hawks** [comment]
because MCMultiPart uses the Capabilities system, instead of using ASM to inject traits like FMP did

**Pull request merged**
