### PR TITLE
Bugfix attempt to remove render lag (see #1457)

### PR DESCRIPTION
**Pull request by tommyTT**
See #1457 for details and concerns that should be adressed before merging.

### CODE REVIEW

**Comment by keraldi** [comment]
While naturally growing the crystal updates it correctly and immediately, removing the crystal by right clicking the cluster (possible while carrying a Tartaric Gem with > 1024 of Raw Will) does not update it.

Same goes for adding crystals manually through creative mode.

Please edit https://github.com/tommyTT/BloodMagic/blob/2e9ad1122b0816f22731f7e75b91a6ade0be40af/src/main/java/WayofTime/bloodmagic/block/BlockDemonCrystal.java#L50 accordingly.

While markdirty() and notifyUpdate() might be meaningless for the visual update, eventListeners should probably still know if something happened there, though @TehNut's say will have more weight on that.

**Comment by TehNut** [comment]
`markDirty()` is called to inform the world that a value has changed and should be written to disk during the next save. Since values are changing, it needs to be called.

**Comment by tommyTT** [comment]
Sorry for the delay, I looked more into the underlying problem and found a more general solution that doesn't require to change 10 places where the tile entity can change.

This now applies to all TileEntities because the method I changed was final. I think this is fine, but you might need to verify and adapt the code accordingly.

**Comment by keraldi** [comment]
Works for me.

This is now obsolete and should be removed:

https://github.com/WayofTime/BloodMagic/blob/348a740c14eb3cefe4e377757a4fec93ea6d88c7/src/main/java/WayofTime/bloodmagic/tile/TileDemonCrystal.java#L133

**Comment by tommyTT** [comment]
I'm not 100% sure and therefore didn't change it, since it is called server side. The notifyUpdate I added is called client side.

**Comment by keraldi** [comment]
Try running your change with the "Crack of the Fractured Crystal" Ritual.

Nvm. Inserted the change at the wrong location :P

**Comment by tommyTT** [comment]
Okay, it seems to update correctly for me.

**Comment by keraldi** [comment]
I tested it as well. Does what it intends to do. No noticable side effects.

Tested in: SSP, local SMP with relevant rituals (rituals that grow or destroy/pop crystals, manual adding and removing crystals).

**Comment by tommyTT** [comment]
The previous solution did fix the issue with the crystals but caused significant lag with the blood altar. The new solution now leaves it up to the tile entity to do the required updates. While extensively testing in SSP and SMP I didn't notice any side effects and the crystal growth issue is also fixed.

**Comment by keraldi** [comment]
Please clean up the PR by cherry-picking the changes you made and putting them into a new branch from upstream.

The file changes dialog shows many changes that had absolutely nothing to do with your original PR.

(i.e. close the PR, branch from upstream, paste your changes, open new PR from the new branch)

**Comment by tommyTT** [comment]
I cleaned it up, so now only the relevant changes should be in the branch. Sorry for the mess.

**Review by keraldi — APPROVED** [review]

**Pull request merged**
