### PR TITLE
#1036 Fixed Living Armor sacrifical upgrade

### PR DESCRIPTION
**Pull request by pksiazek**

### CODE REVIEW

**Comment by TehNut** [comment]
How does removing all the sacrifice code from the dagger fix the Living Armor

**Comment by pksiazek** [comment]
Because this code is unused anyway as I explained in issue.
Current working code is in PlayerSacrificeHelper

**Comment by WayofTime** [comment]
I tested the changes and this makes the dagger not work when you do not have incense.

EDIT: I think only the changes in PlacerSacrificeHelper are needed.

**Comment by pksiazek** [comment]
Damn.
You are completely right.
I fixed PR.

**Pull request merged**
